name: Build - Test - Deployment
run-name: ${{github.actor}} trigger build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install pnpm
        run: |
            npm install -g pnpm &&
            pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install pnpm
        run: |
            npm install -g pnpm &&
            pnpm install --frozen-lockfile
      - name: Run test
        run: |
          pnpm run test:cov
